name: setup
services:
  dev:
    image: ubuntu:22.04
    build:
      context: ./
      dockerfile: ./Dockerfile/Dockerfile
    volumes:
      - type: bind
        source: /home/ubuntu/workspaces/setup
        target: /home/ubuntu/setup
    tty: true
