name: vm
services:
  ubuntu:
    image: ubuntu:22.04
    build:
      context: ./Dockerfile
      args:
        GCLOUD_VERSION: 405.0.0
    volumes:
      - type: volume
        source: vm
        target: /root/github/vm/src
      - type: bind
        source: /home/ubuntu/secret
        target: /root/secret
volumes:
  vm:
    driver: rclone
    driver_opts:
      remote: "onedrive:backup/github/vm/src"
