name: setup
services:
  dev:
    image: setup
    build:
      context: .
      dockerfile: Dockerfile/Dockerfile
    volumes:
      - type: bind
        source: /home/ubuntu/workspaces/setup
        target: /home/ubuntu/workspaces/setup
