name: GITHUB_REPO
services:
  dev:
    image: GITHUB_REPO-dev:latest
    build:
      context: .
      dockerfile: Dockerfile/dev.Dockerfile
    volumes:
      - type: bind
        source: /home/ubuntu/workspaces/GITHUB_REPO
        target: /home/ubuntu/GITHUB_REPO
    working_dir: /home/ubuntu/GITHUB_REPO
  prod:
    image: GITHUB_REPO-prod:latest
    build:
      context: .
      dockerfile: Dockerfile/prod.Dockerfile
